export const jobRoles = [
  "Software Engineer",
  "Engineering Manager",
  "Artificial Intelligence Engineer (AI)",
  "Machine Learning Engineer",
  "Product Manager",
  "Backend Engineer",
  "Mobile Engineer",
  "Product Designer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Data Scientist",
  "Designer",
  "Software Architect",
  "Devops Engineer",
];
